server:
  port: 8080
  servlet:
    session:
      tracking-modes: cookie
      cookie:
        http-only: true
  max-http-header-size: 10000000
  tomcat:
    max-http-form-post-size: 50000000
spring:
  thymeleaf:
    prefix: classpath:/templates/
    mode: HTML
    cache: false
    encoding: utf-8
    servlet:
      content-type: text/html
  datasource:
       driver-class-name: com.mysql.cj.jdbc.Driver
       url: jdbc:mysql://localhost:3306/test100?useUnicode=true&characterEncoding=utf-8
       username: root
       password: 123456
  redis:
       database: 0
       host: 127.0.0.1
       port: 6379
       pool: max-idle=8
             min-idle=0
             max-active=8
             max-wait=-1
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    call-setters-on-nulls: false
    map-underscore-to-camel-case: true
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
chat-file:
  upload-path: C:\Users\lenovo\Desktopfiles\